print('*' * 10 + ' Welcome to Program ' + '*' * 10)
num1 = int(input('Enter number 1 : '))
num2 = int(input('Enter number 2 : '))
print('ADDITION : ' , num1 + num2 )
print('SUBTRACTION : ' , num1 - num2 )
print('MULTIPLICATION : ', num1 * num2 )
print('DIVISION : ' ,num1 / num2 )
print('EXPONENT : ' ,num1 ** num2 )
print('*' * 10 + ' Thanks !! ' + '*' * 10)