print('*' * 10 + ' Welcome to Program ' + '*' * 10)
r = float(input('Enter radius to calculate area of circle : '))
print('AREA OF CIRCLE  : ' , 3.14*r*r )
s = int(input('Enter side to calculate area of square : '))
print('AREA OF SQUARE  : ' , s*s)
l = int(input('Enter length to calculate area of rectangle : '))
b = int(input('Enter breadth to calculate area of rectangle : '))
print('AREA OF RECTANGLE  : ' , l*b )
print('*' * 10 + ' Thanks !! ' + '*' * 10)